-- Wasabi — catalogue d'articles (241 articles).
-- GÉNÉRÉ par _dev/catalogue_sql.py à partir de catalogue.csv : ne pas modifier à la main.
-- Supabase → SQL Editor → New query → coller → Run. Repassable sans danger.

insert into public.catalog_items (name, name_normalized, synonyms, default_aisle_key) values
  ('Bananes', 'bananes', '{}'::text[], 'fruits_legumes'),
  ('Pommes', 'pommes', '{}'::text[], 'fruits_legumes'),
  ('Oranges', 'oranges', '{}'::text[], 'fruits_legumes'),
  ('Clémentines', 'clementines', '{}'::text[], 'fruits_legumes'),
  ('Mandarines', 'mandarines', '{}'::text[], 'fruits_legumes'),
  ('Citrons', 'citrons', '{}'::text[], 'fruits_legumes'),
  ('Limes', 'limes', '{}'::text[], 'fruits_legumes'),
  ('Raisins', 'raisins', '{}'::text[], 'fruits_legumes'),
  ('Fraises', 'fraises', '{}'::text[], 'fruits_legumes'),
  ('Bleuets', 'bleuets', '{}'::text[], 'fruits_legumes'),
  ('Framboises', 'framboises', '{}'::text[], 'fruits_legumes'),
  ('Poires', 'poires', '{}'::text[], 'fruits_legumes'),
  ('Melon d''eau', 'melon d''eau', array['Pastèque'], 'fruits_legumes'),
  ('Cantaloup', 'cantaloup', '{}'::text[], 'fruits_legumes'),
  ('Ananas', 'ananas', '{}'::text[], 'fruits_legumes'),
  ('Avocats', 'avocats', '{}'::text[], 'fruits_legumes'),
  ('Tomates', 'tomates', '{}'::text[], 'fruits_legumes'),
  ('Tomates cerises', 'tomates cerises', '{}'::text[], 'fruits_legumes'),
  ('Concombres', 'concombres', array['Concombre anglais'], 'fruits_legumes'),
  ('Laitue', 'laitue', array['Salade'], 'fruits_legumes'),
  ('Laitue romaine', 'laitue romaine', array['Romaine'], 'fruits_legumes'),
  ('Laitue frisée', 'laitue frisee', '{}'::text[], 'fruits_legumes'),
  ('Laitue iceberg', 'laitue iceberg', array['Iceberg'], 'fruits_legumes'),
  ('Laitue Boston', 'laitue boston', '{}'::text[], 'fruits_legumes'),
  ('Épinards', 'epinards', array['Bébés épinards'], 'fruits_legumes'),
  ('Roquette', 'roquette', '{}'::text[], 'fruits_legumes'),
  ('Carottes', 'carottes', '{}'::text[], 'fruits_legumes'),
  ('Céleri', 'celeri', '{}'::text[], 'fruits_legumes'),
  ('Oignons', 'oignons', array['Onions', 'Oignons jaunes'], 'fruits_legumes'),
  ('Oignons rouges', 'oignons rouges', '{}'::text[], 'fruits_legumes'),
  ('Oignons verts', 'oignons verts', array['Échalotes'], 'fruits_legumes'),
  ('Échalotes françaises', 'echalotes francaises', '{}'::text[], 'fruits_legumes'),
  ('Ail', 'ail', '{}'::text[], 'fruits_legumes'),
  ('Gingembre', 'gingembre', '{}'::text[], 'fruits_legumes'),
  ('Pommes de terre', 'pommes de terre', array['Patates'], 'fruits_legumes'),
  ('Patates douces', 'patates douces', '{}'::text[], 'fruits_legumes'),
  ('Poivrons', 'poivrons', '{}'::text[], 'fruits_legumes'),
  ('Piment fort', 'piment fort', array['Piment', 'Piments', 'Piments forts', 'Jalapeño'], 'fruits_legumes'),
  ('Brocoli', 'brocoli', '{}'::text[], 'fruits_legumes'),
  ('Chou-fleur', 'chou-fleur', '{}'::text[], 'fruits_legumes'),
  ('Champignons', 'champignons', '{}'::text[], 'fruits_legumes'),
  ('Courgettes', 'courgettes', array['Zucchinis'], 'fruits_legumes'),
  ('Maïs', 'mais', array['Blé d''Inde'], 'fruits_legumes'),
  ('Haricots verts', 'haricots verts', array['Fèves vertes'], 'fruits_legumes'),
  ('Asperges', 'asperges', '{}'::text[], 'fruits_legumes'),
  ('Chou', 'chou', '{}'::text[], 'fruits_legumes'),
  ('Chou kale', 'chou kale', array['Kale'], 'fruits_legumes'),
  ('Courge', 'courge', '{}'::text[], 'fruits_legumes'),
  ('Courge musquée', 'courge musquee', array['Courge butternut', 'Butternut'], 'fruits_legumes'),
  ('Courge spaghetti', 'courge spaghetti', '{}'::text[], 'fruits_legumes'),
  ('Courge poivrée', 'courge poivree', '{}'::text[], 'fruits_legumes'),
  ('Coriandre', 'coriandre', '{}'::text[], 'fruits_legumes'),
  ('Persil', 'persil', '{}'::text[], 'fruits_legumes'),
  ('Basilic', 'basilic', '{}'::text[], 'fruits_legumes'),
  ('Tofu', 'tofu', '{}'::text[], 'fruits_legumes'),
  ('Pain', 'pain', array['Pain tranché'], 'boulangerie'),
  ('Baguette', 'baguette', array['Pain baguette'], 'boulangerie'),
  ('Bagels', 'bagels', '{}'::text[], 'boulangerie'),
  ('Muffins anglais', 'muffins anglais', '{}'::text[], 'boulangerie'),
  ('Tortillas', 'tortillas', array['Wraps'], 'boulangerie'),
  ('Pains à hamburger', 'pains a hamburger', '{}'::text[], 'boulangerie'),
  ('Pains à hot-dog', 'pains a hot-dog', '{}'::text[], 'boulangerie'),
  ('Pitas', 'pitas', array['Pains pita'], 'boulangerie'),
  ('Pain naan', 'pain naan', array['Naan'], 'boulangerie'),
  ('Croissants', 'croissants', '{}'::text[], 'boulangerie'),
  ('Fromage parmesan', 'fromage parmesan', array['Parmesan'], 'fromages_fins'),
  ('Fromage feta', 'fromage feta', array['Feta'], 'fromages_fins'),
  ('Fromage de chèvre', 'fromage de chevre', '{}'::text[], 'fromages_fins'),
  ('Houmous', 'houmous', array['Hummus'], 'fromages_fins'),
  ('Fromage brie', 'fromage brie', array['Brie'], 'fromages_fins'),
  ('Fromage bleu', 'fromage bleu', '{}'::text[], 'fromages_fins'),
  ('Bocconcini', 'bocconcini', '{}'::text[], 'fromages_fins'),
  ('Tzatziki', 'tzatziki', '{}'::text[], 'fromages_fins'),
  ('Trempette', 'trempette', '{}'::text[], 'fromages_fins'),
  ('Olives', 'olives', '{}'::text[], 'fromages_fins'),
  ('Prosciutto', 'prosciutto', '{}'::text[], 'fromages_fins'),
  ('Salami', 'salami', '{}'::text[], 'fromages_fins'),
  ('Poulet', 'poulet', array['Poitrines de poulet'], 'viandes_poissons'),
  ('Hauts de cuisse de poulet', 'hauts de cuisse de poulet', array['Cuisses de poulet'], 'viandes_poissons'),
  ('Poulet entier', 'poulet entier', array['Poulet rôti'], 'viandes_poissons'),
  ('Bœuf haché', 'boeuf hache', array['Steak haché'], 'viandes_poissons'),
  ('Steak', 'steak', array['Bifteck'], 'viandes_poissons'),
  ('Porc haché', 'porc hache', '{}'::text[], 'viandes_poissons'),
  ('Filet de porc', 'filet de porc', '{}'::text[], 'viandes_poissons'),
  ('Côtelettes de porc', 'cotelettes de porc', '{}'::text[], 'viandes_poissons'),
  ('Bacon', 'bacon', '{}'::text[], 'viandes_poissons'),
  ('Saucisses', 'saucisses', '{}'::text[], 'viandes_poissons'),
  ('Jambon', 'jambon', array['Jambon tranché'], 'viandes_poissons'),
  ('Dinde tranchée', 'dinde tranchee', '{}'::text[], 'viandes_poissons'),
  ('Saumon', 'saumon', '{}'::text[], 'viandes_poissons'),
  ('Saumon fumé', 'saumon fume', '{}'::text[], 'viandes_poissons'),
  ('Crevettes', 'crevettes', '{}'::text[], 'viandes_poissons'),
  ('Morue', 'morue', '{}'::text[], 'viandes_poissons'),
  ('Tilapia', 'tilapia', '{}'::text[], 'viandes_poissons'),
  ('Sole', 'sole', '{}'::text[], 'viandes_poissons'),
  ('Aiglefin', 'aiglefin', '{}'::text[], 'viandes_poissons'),
  ('Truite', 'truite', '{}'::text[], 'viandes_poissons'),
  ('Pétoncles', 'petoncles', '{}'::text[], 'viandes_poissons'),
  ('Moules', 'moules', '{}'::text[], 'viandes_poissons'),
  ('Pâtes', 'pates', '{}'::text[], 'garde_manger'),
  ('Spaghetti', 'spaghetti', '{}'::text[], 'garde_manger'),
  ('Spaghettini', 'spaghettini', '{}'::text[], 'garde_manger'),
  ('Macaroni', 'macaroni', '{}'::text[], 'garde_manger'),
  ('Penne', 'penne', '{}'::text[], 'garde_manger'),
  ('Fusilli', 'fusilli', '{}'::text[], 'garde_manger'),
  ('Linguine', 'linguine', '{}'::text[], 'garde_manger'),
  ('Lasagne', 'lasagne', array['Pâtes à lasagne'], 'garde_manger'),
  ('Orzo', 'orzo', '{}'::text[], 'garde_manger'),
  ('Nouilles de riz', 'nouilles de riz', array['Vermicelles de riz'], 'garde_manger'),
  ('Nouilles ramen', 'nouilles ramen', array['Ramen'], 'garde_manger'),
  ('Riz', 'riz', '{}'::text[], 'garde_manger'),
  ('Quinoa', 'quinoa', '{}'::text[], 'garde_manger'),
  ('Couscous', 'couscous', '{}'::text[], 'garde_manger'),
  ('Sauce tomate', 'sauce tomate', array['Sauce à spaghetti'], 'garde_manger'),
  ('Tomates en conserve', 'tomates en conserve', array['Tomates en dés'], 'garde_manger'),
  ('Pâte de tomate', 'pate de tomate', '{}'::text[], 'garde_manger'),
  ('Bouillon de poulet', 'bouillon de poulet', array['Bouillon'], 'garde_manger'),
  ('Thon en conserve', 'thon en conserve', array['Thon'], 'garde_manger'),
  ('Pois chiches', 'pois chiches', '{}'::text[], 'garde_manger'),
  ('Haricots noirs', 'haricots noirs', array['Fèves noires'], 'garde_manger'),
  ('Lentilles', 'lentilles', '{}'::text[], 'garde_manger'),
  ('Maïs en conserve', 'mais en conserve', '{}'::text[], 'garde_manger'),
  ('Soupe en conserve', 'soupe en conserve', array['Soupe'], 'garde_manger'),
  ('Lait de coco', 'lait de coco', '{}'::text[], 'garde_manger'),
  ('Huile d''olive', 'huile d''olive', '{}'::text[], 'garde_manger'),
  ('Huile végétale', 'huile vegetale', array['Huile de canola'], 'garde_manger'),
  ('Vinaigre', 'vinaigre', array['Vinaigre blanc'], 'garde_manger'),
  ('Vinaigre balsamique', 'vinaigre balsamique', '{}'::text[], 'garde_manger'),
  ('Ketchup', 'ketchup', '{}'::text[], 'garde_manger'),
  ('Moutarde jaune', 'moutarde jaune', array['Moutarde', 'Moutarde préparée'], 'garde_manger'),
  ('Moutarde de Dijon', 'moutarde de dijon', array['Dijon'], 'garde_manger'),
  ('Moutarde à l''ancienne', 'moutarde a l''ancienne', array['Moutarde de Meaux'], 'garde_manger'),
  ('Mayonnaise', 'mayonnaise', '{}'::text[], 'garde_manger'),
  ('Sauce soya', 'sauce soya', array['Sauce soja'], 'garde_manger'),
  ('Salsa', 'salsa', '{}'::text[], 'garde_manger'),
  ('Vinaigrette', 'vinaigrette', '{}'::text[], 'garde_manger'),
  ('Sel', 'sel', '{}'::text[], 'garde_manger'),
  ('Poivre', 'poivre', '{}'::text[], 'garde_manger'),
  ('Cannelle', 'cannelle', '{}'::text[], 'garde_manger'),
  ('Cumin', 'cumin', '{}'::text[], 'garde_manger'),
  ('Paprika', 'paprika', '{}'::text[], 'garde_manger'),
  ('Poudre d''ail', 'poudre d''ail', '{}'::text[], 'garde_manger'),
  ('Poudre d''oignon', 'poudre d''oignon', '{}'::text[], 'garde_manger'),
  ('Origan', 'origan', '{}'::text[], 'garde_manger'),
  ('Poudre de chili', 'poudre de chili', '{}'::text[], 'garde_manger'),
  ('Cari', 'cari', array['Curry'], 'garde_manger'),
  ('Herbes de Provence', 'herbes de provence', '{}'::text[], 'garde_manger'),
  ('Sirop d''érable', 'sirop d''erable', '{}'::text[], 'garde_manger'),
  ('Miel', 'miel', '{}'::text[], 'garde_manger'),
  ('Farine', 'farine', '{}'::text[], 'garde_manger'),
  ('Sucre', 'sucre', '{}'::text[], 'garde_manger'),
  ('Cassonade', 'cassonade', array['Sucre brun'], 'garde_manger'),
  ('Poudre à pâte', 'poudre a pate', '{}'::text[], 'garde_manger'),
  ('Bicarbonate de soude', 'bicarbonate de soude', array['Soda à pâte', 'Petite vache'], 'garde_manger'),
  ('Vanille', 'vanille', array['Extrait de vanille'], 'garde_manger'),
  ('Pépites de chocolat', 'pepites de chocolat', array['Brisures de chocolat'], 'garde_manger'),
  ('Flocons d''avoine', 'flocons d''avoine', array['Gruau'], 'garde_manger'),
  ('Céréales', 'cereales', '{}'::text[], 'garde_manger'),
  ('Beurre d''arachide', 'beurre d''arachide', array['Beurre de peanut', 'Beurre d''arachides'], 'garde_manger'),
  ('Confiture', 'confiture', '{}'::text[], 'garde_manger'),
  ('Tartinade aux noisettes', 'tartinade aux noisettes', array['Nutella'], 'garde_manger'),
  ('Craquelins', 'craquelins', array['Biscuits soda'], 'garde_manger'),
  ('Chips', 'chips', array['Croustilles'], 'garde_manger'),
  ('Barres tendres', 'barres tendres', array['Barres granola'], 'garde_manger'),
  ('Noix', 'noix', array['Amandes', 'Noix mélangées'], 'garde_manger'),
  ('Biscuits', 'biscuits', '{}'::text[], 'garde_manger'),
  ('Chocolat', 'chocolat', '{}'::text[], 'garde_manger'),
  ('Maïs soufflé', 'mais souffle', array['Popcorn'], 'garde_manger'),
  ('Raisins secs', 'raisins secs', '{}'::text[], 'garde_manger'),
  ('Tisane', 'tisane', '{}'::text[], 'garde_manger'),
  ('Thé', 'the', '{}'::text[], 'garde_manger'),
  ('Café', 'cafe', '{}'::text[], 'garde_manger'),
  ('Fromage cheddar', 'fromage cheddar', array['Cheddar'], 'laitiers_oeufs'),
  ('Fromage mozzarella', 'fromage mozzarella', array['Mozzarella'], 'laitiers_oeufs'),
  ('Fromage en grains', 'fromage en grains', array['Crottes de fromage'], 'laitiers_oeufs'),
  ('Lait', 'lait', '{}'::text[], 'laitiers_oeufs'),
  ('Œufs', 'oeufs', '{}'::text[], 'laitiers_oeufs'),
  ('Beurre', 'beurre', '{}'::text[], 'laitiers_oeufs'),
  ('Yogourt', 'yogourt', array['Yaourt'], 'laitiers_oeufs'),
  ('Yogourt grec', 'yogourt grec', '{}'::text[], 'laitiers_oeufs'),
  ('Crème', 'creme', array['Crème à cuisson', 'Crème 15 %', 'Crème 35 %'], 'laitiers_oeufs'),
  ('Crème sure', 'creme sure', '{}'::text[], 'laitiers_oeufs'),
  ('Fromage à la crème', 'fromage a la creme', array['Philadelphia'], 'laitiers_oeufs'),
  ('Fromage cottage', 'fromage cottage', '{}'::text[], 'laitiers_oeufs'),
  ('Boisson d''amande', 'boisson d''amande', array['Lait d''amande'], 'laitiers_oeufs'),
  ('Boisson d''avoine', 'boisson d''avoine', array['Lait d''avoine'], 'laitiers_oeufs'),
  ('Margarine', 'margarine', '{}'::text[], 'laitiers_oeufs'),
  ('Jus d''orange', 'jus d''orange', '{}'::text[], 'boissons'),
  ('Jus de pomme', 'jus de pomme', '{}'::text[], 'boissons'),
  ('Eau pétillante', 'eau petillante', array['Eau gazéifiée', 'Bubly', 'Perrier'], 'boissons'),
  ('Boisson gazeuse', 'boisson gazeuse', array['Liqueur', 'Coke', 'Pepsi'], 'boissons'),
  ('Eau en bouteille', 'eau en bouteille', array['Eau'], 'boissons'),
  ('Bière', 'biere', '{}'::text[], 'boissons'),
  ('Vin rouge', 'vin rouge', '{}'::text[], 'boissons'),
  ('Vin blanc', 'vin blanc', '{}'::text[], 'boissons'),
  ('Cidre', 'cidre', '{}'::text[], 'boissons'),
  ('Légumes surgelés', 'legumes surgeles', '{}'::text[], 'surgeles'),
  ('Fruits surgelés', 'fruits surgeles', array['Petits fruits surgelés'], 'surgeles'),
  ('Pizza surgelée', 'pizza surgelee', array['Pizza congelée'], 'surgeles'),
  ('Crème glacée', 'creme glacee', '{}'::text[], 'surgeles'),
  ('Frites surgelées', 'frites surgelees', array['Frites'], 'surgeles'),
  ('Edamames', 'edamames', '{}'::text[], 'surgeles'),
  ('Gaufres surgelées', 'gaufres surgelees', array['Gaufres'], 'surgeles'),
  ('Pâte à tarte', 'pate a tarte', '{}'::text[], 'surgeles'),
  ('Papier hygiénique', 'papier hygienique', array['Papier de toilette'], 'maison_hygiene'),
  ('Essuie-tout', 'essuie-tout', array['Scott towels'], 'maison_hygiene'),
  ('Mouchoirs', 'mouchoirs', array['Kleenex'], 'maison_hygiene'),
  ('Savon à vaisselle', 'savon a vaisselle', '{}'::text[], 'maison_hygiene'),
  ('Détergent à lessive', 'detergent a lessive', array['Savon à linge', 'Savon à lessive'], 'maison_hygiene'),
  ('Pastilles pour lave-vaisselle', 'pastilles pour lave-vaisselle', array['Savon à lave-vaisselle'], 'maison_hygiene'),
  ('Sacs à ordures', 'sacs a ordures', array['Sacs à poubelle', 'Sacs à vidanges'], 'maison_hygiene'),
  ('Sacs de compost', 'sacs de compost', '{}'::text[], 'maison_hygiene'),
  ('Papier d''aluminium', 'papier d''aluminium', '{}'::text[], 'maison_hygiene'),
  ('Pellicule plastique', 'pellicule plastique', array['Saran wrap'], 'maison_hygiene'),
  ('Papier parchemin', 'papier parchemin', '{}'::text[], 'maison_hygiene'),
  ('Sacs à sandwich', 'sacs a sandwich', array['Sacs Ziploc', 'Ziploc'], 'maison_hygiene'),
  ('Éponges', 'eponges', '{}'::text[], 'maison_hygiene'),
  ('Nettoyant tout usage', 'nettoyant tout usage', '{}'::text[], 'maison_hygiene'),
  ('Dentifrice', 'dentifrice', array['Pâte à dents'], 'maison_hygiene'),
  ('Brosse à dents', 'brosse a dents', '{}'::text[], 'maison_hygiene'),
  ('Soie dentaire', 'soie dentaire', '{}'::text[], 'maison_hygiene'),
  ('Shampoing', 'shampoing', array['Shampooing'], 'maison_hygiene'),
  ('Revitalisant', 'revitalisant', '{}'::text[], 'maison_hygiene'),
  ('Savon pour le corps', 'savon pour le corps', array['Gel douche'], 'maison_hygiene'),
  ('Savon à mains', 'savon a mains', '{}'::text[], 'maison_hygiene'),
  ('Déodorant', 'deodorant', array['Antisudorifique'], 'maison_hygiene'),
  ('Rasoirs', 'rasoirs', array['Lames de rasoir'], 'maison_hygiene'),
  ('Crème solaire', 'creme solaire', '{}'::text[], 'maison_hygiene'),
  ('Tylenol', 'tylenol', array['Acétaminophène'], 'maison_hygiene'),
  ('Advil', 'advil', array['Ibuprofène'], 'maison_hygiene'),
  ('Pansements', 'pansements', array['Plasters', 'Band-Aid'], 'maison_hygiene'),
  ('Tampons', 'tampons', array['Serviettes hygiéniques'], 'maison_hygiene'),
  ('Cotons-tiges', 'cotons-tiges', array['Q-tips'], 'maison_hygiene'),
  ('Couches', 'couches', '{}'::text[], 'bebe'),
  ('Lingettes pour bébé', 'lingettes pour bebe', array['Lingettes'], 'bebe'),
  ('Purées pour bébé', 'purees pour bebe', '{}'::text[], 'bebe'),
  ('Préparation pour nourrissons', 'preparation pour nourrissons', array['Lait maternisé', 'Formule pour bébé'], 'bebe'),
  ('Nourriture pour chat', 'nourriture pour chat', '{}'::text[], 'animaux'),
  ('Nourriture pour chien', 'nourriture pour chien', '{}'::text[], 'animaux'),
  ('Litière', 'litiere', array['Litière à chat'], 'animaux'),
  ('Gâteries pour animaux', 'gateries pour animaux', '{}'::text[], 'animaux')
on conflict (name_normalized) do update
  set name = excluded.name,
      synonyms = excluded.synonyms,
      default_aisle_key = excluded.default_aisle_key;
