// Toutes les chaînes de l'interface, regroupées ici (français du Québec).
// Pas d'infrastructure i18n : ce fichier suffit à en faciliter l'ajout un jour.

const pluriel = (n, mot) => `${n} ${mot}${n > 1 ? "s" : ""}`;

export const T = {
  app: "Wasabi",
  slogan: "L'épicerie et les recettes du foyer.",

  onglets: { epicerie: "Épicerie", recettes: "Recettes", reglages: "Réglages" },

  // Connexion
  courriel: "Ton courriel",
  courrielExemple: "nom@exemple.com",
  motDePasse: "Mot de passe",
  continuer: "Continuer",
  connexionEnCours: "Connexion…",
  premiereConnexion: "Première connexion ? Entre un courriel et un mot de passe pour créer ton compte.",
  courrielInvalide: "Entre un courriel valide",
  motDePasseCourt: "Mot de passe : au moins 6 caractères",
  motDePasseIncorrect: "Mot de passe incorrect",
  confirmationCourriel: "Désactive « Confirm email » dans Supabase, puis réessaie.",

  // Foyer
  bienvenue: "Bienvenue !",
  bienvenueTexte: "Crée ton foyer, ou rejoins-en un avec son code d'invitation.",
  tonPrenom: "Ton prénom",
  prenomExemple: "Maxime",
  creerFoyer: "Créer un foyer",
  ouRejoindre: "…ou rejoindre avec un code",
  rejoindreFoyer: "Rejoindre ce foyer",
  entrePrenom: "Entre ton prénom",
  entreCode: "Entre le code du foyer",
  codeIntrouvable: "Code introuvable",
  foyerPlein: "Ce foyer est complet",
  foyerParDefaut: "Notre foyer",

  // Réglages
  nomDuFoyer: "Nom du foyer",
  enregistrer: "Enregistrer",
  entreNomFoyer: "Entre un nom de foyer",
  nomFoyerMisAJour: "Nom du foyer mis à jour",
  codeInvitation: "Code d'invitation",
  codeInvitationAide: "Partage ce code : l'autre personne choisit « Rejoindre ce foyer » et l'entre.",
  copier: "Copier",
  codeCopie: "Code copié",
  membres: "Membres",
  toi: "toi",
  synchro: "Synchronisation",
  aJour: "Tout est à jour",
  jamaisSynchronise: "Pas encore synchronisé",
  seDeconnecter: "Se déconnecter",
  deconnexionEnAttente: (n) => `${pluriel(n, "changement")} pas encore envoyé${n > 1 ? "s" : ""} : ils seront perdus. Se déconnecter quand même ?`,

  // Épicerie — listes
  nouvelleListe: "Nouvelle liste",
  modifierListe: "Modifier la liste",
  aucuneListe: "Aucune liste pour l'instant. Crée la première : « Épicerie », « Costco », « Chalet »…",
  nomDeLaListe: "Nom de la liste",
  nomDeLaListeExemple: "Épicerie",
  entreNomListe: "Entre un nom de liste",
  emoji: "Emoji",
  emojiAide: "Touche la case, puis choisis un emoji avec le clavier 🙂 de ton téléphone.",
  aideOrdreListes: "Garde le doigt sur une liste pour la déplacer.",
  supprimerListe: "Supprimer la liste",
  confirmerSupprimerListe: (nom) => `Supprimer la liste « ${nom} » et tous ses articles ?`,
  restants: (n) => `${n} à ramasser`,
  rienARamasser: "Rien à ramasser",
  toutesLesListes: "Toutes les listes",
  menuListe: "Options de la liste",

  // Épicerie — articles
  listeVide: "Liste vide. Ajoute ton premier article en bas.",
  ajouterUnArticle: "Ajouter un article",
  ajouter: "Ajouter",
  dejaDansLaListe: "déjà dans la liste",
  moins: "Moins",
  plus: "Plus",
  toutCocher: "Tout cocher",
  toutDecocher: "Tout décocher",
  effacerCoches: "Effacer les cochés",
  aucunCoche: "Aucun article coché",
  cochesEffaces: (n) => `${pluriel(n, "article")} effacé${n > 1 ? "s" : ""}`,
  note: "Note",
  noteExemple: "Marque, type… (ex. à fouetter, sans lactose)",
  allee: "Allée",
  choisirAllee: "Le choix est retenu pour les prochaines fois.",
  autre: "Autre",
  retirerDeLaListe: "Retirer de la liste",

  // Réglages — allées
  allees: "Allées",
  aideAllees: "L'ordre est celui des listes. Garde le doigt sur une allée pour la déplacer. « Autre » reste en dernier.",
  ajouterAllee: "Ajouter une allée",
  modifierAllee: "Modifier l'allée",
  nomAllee: "Nom de l'allée",
  entreNomAllee: "Entre un nom d'allée",
  supprimerAllee: "Supprimer l'allée",
  confirmerSupprimerAllee: (nom, n) => `Supprimer l'allée « ${nom} » ?` + (n ? ` Ses ${pluriel(n, "article")} iront dans « Autre ».` : ""),

  // Réglages — mes articles
  mesArticles: "Mes articles",
  chercherArticle: "Chercher un article",
  aucunArticle: "Aucun article mémorisé pour l'instant : ils s'ajoutent d'eux-mêmes à mesure que tu remplis tes listes.",
  aucunResultat: "Aucun article ne correspond.",
  nomArticle: "Nom de l'article",
  entreNomArticle: "Entre un nom d'article",
  articleExisteDeja: (nom) => `« ${nom} » existe déjà`,
  oublierArticle: "Oublier cet article",

  // Recettes
  ajouterRecette: "Ajouter une recette",
  typesRecette: { url: "Lien vers un site", manual: "Recette écrite à la main", file: "Photo ou PDF" },
  chercherRecette: "Chercher une recette",
  toutes: "Toutes",
  tags: "Tags",
  tagsActifs: (n) => `${pluriel(n, "tag")}`,
  filtrerParTags: "Filtrer par tags",
  filtrerParTagsAide: "Les recettes affichées ont tous les tags choisis.",
  fermer: "Fermer",
  aucuneRecette: "Ton carnet est vide. Touche « + » pour ajouter ta première recette : un lien, une recette écrite, ou la photo d'une page.",
  aucuneRecetteTrouvee: "Aucune recette ne correspond.",
  voirFiche: "Voir la fiche",
  modifier: "Modifier",
  annuler: "Annuler",
  ouvrirRecette: "Ouvrir la recette",
  ingredients: "Ingrédients",
  etapes: "Étapes",
  notes: "Notes",
  notesExemple: "Ajustements, idées, à refaire…",
  page: (n) => `Page ${n}`,
  lien: "Lien",
  coller: "Coller",
  titre: "Titre",
  photo: "Photo",
  imageTuile: "Image de la tuile",
  photosOuPdf: "Photos ou PDF",
  choisirPhoto: "Choisir une photo",
  changerPhoto: "Changer",
  retirer: "Retirer",
  prendrePhoto: "Prendre une photo",
  choisirFichiers: "Choisir des fichiers",
  categorie: "Catégorie",
  aucuneCategorie: "Aucune",
  nouveauTag: "Nouveau tag",
  apercuEnCours: "Recherche du titre et de l'image…",
  apercuEchec: "Aperçu impossible pour ce site : complète à la main.",
  lienInvalide: "Entre un lien valide (https://…)",
  entreTitre: "Entre un titre",
  ajouteUnFichier: "Ajoute au moins une photo ou un PDF",
  fichierRefuse: "Seulement des images ou des PDF",
  pdfTropLourd: "Ce PDF dépasse 25 Mo",
  rienAColler: "Aucun lien dans le presse-papier",
  collerALaMain: "Colle le lien dans le champ (toucher long → Coller)",
  enregistrementEnCours: "Enregistrement…",
  enregistrementImpossible: "Enregistrement impossible — réessaie",
  recetteEnregistree: "Recette enregistrée",
  supprimerRecette: "Supprimer la recette",
  confirmerSupprimerRecette: (titre) => `Supprimer « ${titre} » du carnet ?`,
  fichierIndisponible: "Fichier pas encore sur cet appareil. Il s'affichera au retour du réseau.",
  ouvrirPdf: "Ouvrir le PDF en plein écran",
  pagePrecedente: "Page précédente",
  pageSuivante: "Page suivante",

  // Réglages — catégories et tags
  categoriesRecettes: "Catégories de recettes",
  tagsRecettes: "Tags de recettes",
  ajouterCategorie: "Ajouter une catégorie",
  ajouterTag: "Ajouter un tag",
  aideCategories: "Garde le doigt sur une catégorie pour la déplacer.",
  aideTags: "Les tags se créent aussi directement en ajoutant une recette.",
  nom: "Nom",
  entreNom: "Entre un nom",
  supprimer: "Supprimer",
  confirmerSupprimerNomme: (nom) => `Supprimer « ${nom} » ? Aucune recette n'est supprimée.`,

  // Écrans à venir

  // Réseau
  horsLigne: "Hors ligne",
  aEnvoyer: (n) => `${pluriel(n, "changement")} à envoyer`,
  envoiEnCours: (n) => `Envoi de ${pluriel(n, "changement")}…`,
  aJourA: (heure) => ` — à jour à ${heure}`,
  aJourLe: (jour, heure) => ` — à jour le ${jour} à ${heure}`,
  pasEnregistre: (msg) => `Pas enregistré : ${msg}`,
  chargementImpossible: "Impossible de charger les données — vérifie la connexion",
  pasDeReseau: "Pas de réseau",
  pasDeReseauTexte: "Wasabi n'arrive pas à joindre le serveur. La prochaine fois, tes listes s'afficheront même hors ligne.",
  reessayer: "Réessayer",

  // Configuration manquante
  configTitre: "Presque prêt",
  configTexte: "L'app n'est pas encore reliée à Supabase. Ouvre lib/config.js et colle l'adresse du projet (Project URL).",
};
